export const users = [
    {
      "id": "1",
      "organization": "Zenith Technologies",
      "username": "chuks_99",
      "email": "chuks99@example.com",
      "phoneNumber": "+2348012345678",
      "dateJoined": "2023-05-14",
      "status": "Active",
      "fullName": "Chukwuma Eze",
      "bvn": "22334455667",
      "gender": "Male",
      "maritalStatus": "Single",
      "children": "0",
      "residenceType": "Rented Apartment",
      "levelOfEducation": "B.Sc",
      "employmentStatus": "Employed",
      "sectorOfEmployment": "Information Technology",
      "durationOfEmployment": "3 years",
      "officeEmail": "chuks.eze@zenithtech.com",
      "monthlyIncome": "₦250,000 - ₦350,000",
      "loanRepayment": "₦15,000",
      "twitter": "@chuks_99",
      "facebook": "facebook.com/chuks99",
      "instagram": "@chuks_99",
      "guarantorName": "Ifeanyi Okeke",
      "guarantorPhoneNumber": "+2348098765432",
      "guarantorEmail": "ifeanyi.okeke@example.com",
      "guarantorRelationship": "Brother"
    },
    {
      "id": "2",
      "organization": "Access Microfinance",
      "username": "amina_k",
      "email": "amina.k@example.com",
      "phoneNumber": "+2348023456789",
      "dateJoined": "2022-11-02",
      "status": "Pending",
      "fullName": "Amina Kabir",
      "bvn": "33445566778",
      "gender": "Female",
      "maritalStatus": "Married",
      "children": "2",
      "residenceType": "Family House",
      "levelOfEducation": "M.Sc",
      "employmentStatus": "Self-Employed",
      "sectorOfEmployment": "Fashion & Design",
      "durationOfEmployment": "5 years",
      "officeEmail": "contact@aminakdesigns.com",
      "monthlyIncome": "₦400,000 - ₦600,000",
      "loanRepayment": "₦25,000",
      "twitter": "@amina_k",
      "facebook": "facebook.com/amina.k",
      "instagram": "@amina_k_designs",
      "guarantorName": "Fatima Kabir",
      "guarantorPhoneNumber": "+2348031234567",
      "guarantorEmail": "fatima.kabir@example.com",
      "guarantorRelationship": "Sister"
    },
    {
      "id": "2",
      "organization": "Access Microfinance",
      "username": "amina_k",
      "email": "amina.k@example.com",
      "phoneNumber": "+2348023456789",
      "dateJoined": "2022-11-02",
      "status": "Active",
      "fullName": "Amina Kabir",
      "bvn": "33445566778",
      "gender": "Female",
      "maritalStatus": "Married",
      "children": "2",
      "residenceType": "Family House",
      "levelOfEducation": "M.Sc",
      "employmentStatus": "Self-Employed",
      "sectorOfEmployment": "Fashion & Design",
      "durationOfEmployment": "5 years",
      "officeEmail": "contact@aminakdesigns.com",
      "monthlyIncome": "₦400,000 - ₦600,000",
      "loanRepayment": "₦25,000",
      "twitter": "@amina_k",
      "facebook": "facebook.com/amina.k",
      "instagram": "@amina_k_designs",
      "guarantorName": "Fatima Kabir",
      "guarantorPhoneNumber": "+2348031234567",
      "guarantorEmail": "fatima.kabir@example.com",
      "guarantorRelationship": "Sister"
    },
    {
      "id": "2",
      "organization": "Access Microfinance",
      "username": "amina_k",
      "email": "amina.k@example.com",
      "phoneNumber": "+2348023456789",
      "dateJoined": "2022-11-02",
      "status": "Blacklisted",
      "fullName": "Amina Kabir",
      "bvn": "33445566778",
      "gender": "Female",
      "maritalStatus": "Married",
      "children": "2",
      "residenceType": "Family House",
      "levelOfEducation": "M.Sc",
      "employmentStatus": "Self-Employed",
      "sectorOfEmployment": "Fashion & Design",
      "durationOfEmployment": "5 years",
      "officeEmail": "contact@aminakdesigns.com",
      "monthlyIncome": "₦400,000 - ₦600,000",
      "loanRepayment": "₦25,000",
      "twitter": "@amina_k",
      "facebook": "facebook.com/amina.k",
      "instagram": "@amina_k_designs",
      "guarantorName": "Fatima Kabir",
      "guarantorPhoneNumber": "+2348031234567",
      "guarantorEmail": "fatima.kabir@example.com",
      "guarantorRelationship": "Sister"
    },
    {
      "id": "2",
      "organization": "Access Microfinance",
      "username": "amina_k",
      "email": "amina.k@example.com",
      "phoneNumber": "+2348023456789",
      "dateJoined": "2022-11-02",
      "status": "Inactive",
      "fullName": "Amina Kabir",
      "bvn": "33445566778",
      "gender": "Female",
      "maritalStatus": "Married",
      "children": "2",
      "residenceType": "Family House",
      "levelOfEducation": "M.Sc",
      "employmentStatus": "Self-Employed",
      "sectorOfEmployment": "Fashion & Design",
      "durationOfEmployment": "5 years",
      "officeEmail": "contact@aminakdesigns.com",
      "monthlyIncome": "₦400,000 - ₦600,000",
      "loanRepayment": "₦25,000",
      "twitter": "@amina_k",
      "facebook": "facebook.com/amina.k",
      "instagram": "@amina_k_designs",
      "guarantorName": "Fatima Kabir",
      "guarantorPhoneNumber": "+2348031234567",
      "guarantorEmail": "fatima.kabir@example.com",
      "guarantorRelationship": "Sister"
    }
  ];  